version: "3"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - TZ=${TZ}
    volumes:
      - /storage01/mediacenter/plex/config:/config
      - /storage03/mediacenter/plex/media/peliculas:/data/peliculas
      - /storage03/mediacenter/plex/media/series:/data/series

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=warning
    volumes:
      - /storage01/mediacenter/deluge/config:/config
      - /storage01/mediacenter/deluge/downloads:/downloads
    ports:
      - 8112:8112 # webui
      - 6881:6881 # Inbound torrent traffic
      - 6881:6881/udp # Inbound torrent traffic
      - 58846:58846 # Default deluged port for thin client connectivity

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=false
    volumes:
      - /storage01/mediacenter/jackett/config:/config
    ports:
      - 9117:9117
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /storage01/mediacenter/sonarr/config:/config
      - /storage01/mediacenter/deluge/downloads:/downloads
      - /storage03/mediacenter/plex/media/series:/data/series
    ports:
      - 8989:8989
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /storage01/mediacenter/radarr/config:/config
      - /storage01/mediacenter/deluge/downloads:/downloads
      - /storage03/mediacenter/plex/media/peliculas:/data/peliculas
    ports:
      - 7878:7878
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /storage01/mediacenter/bazarr/config:/config
      - /storage01/mediacenter/deluge/downloads:/downloads
      - /storage03/mediacenter/plex/media/series:/data/series
      - /storage03/mediacenter/plex/media/peliculas:/data/peliculas
    ports:
      - 6767:6767